- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/MavenAnsibleWebAppCICD/target/MavenAnsibleWebapp1.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebapp1.war"
        remote_src: no
      become: no
    - name:  Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
      become_user: root
