- name: Deploy to Tomcat
  hosts: web
  become: yes
  vars:
    ansible_become_password: "server123"
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/MavenAnsibleWebAppCICD/target/MavenAnsibleWebapp.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebapp.war"
        remote_src: yes
    - name:  Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
